### ISSUE TITLE
Roadmap for final V02 data sets

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/its_live_production#15]
Image pair velocities:
- [ ] Get summary of metadata changes to Joe (@mliukis)
- [ ] Implement metadata changes (@jhkennedy)
- [ ] Production runs (@jhkennedy)
- [ ] Prepare data for NSIDC ingest: documentation (@alex-s-gardner , @mliukis)

Mosaics:
- [ ] Generate datacubes (@mliukis)
- [ ] Generate composites:
        * Finalize stable_shift filter (@alex-s-gardner , @mliukis)
        * Add filter to get rid of v0 outliers (@alex-s-gardner , @mliukis)
- [ ] Generate mosaics:
        * Define regions: which cubes are included into which mosaics (@alex-s-gardner)
        * Prepare data for NSIDC ingest: documentation (@alex-s-gardner , @mliukis)

**Comment by mliukis** [comment]
Done
