### ISSUE TITLE
Final roadmap for V2 data products

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/its_live_production#16]
**Finish granule processing:**

- [x] Finish remaining L7 processing @jhkennedy 
- [x] Transfer granules to s3://its-live-data @mliukis

**Fix S1 granules:**

- [x] develop and validate S1 correction workflow @mliukis 
- [x] provide list of S1 granules that need correction @mliukis 
Then either:
- [x] correct granules:
  - [x] create intermediate files for all reference tracks @jhkennedy 
  - [x] provide table linking reference tracks to each granule @jhkennedy 
  - [x] apply correction to old S1 granules @mliukis 
* ~~or re-process granules~~
  - ~~reprocess all granules that need correction @jhkennedy~~ 
  - ~~delete S1 granules that need correction @mliukis~~
  - ~~Transfer newly-processed granules to s3://its-live-data @mliukis~~

**Fix Landsat 7**

- [x] provide example data for percent valid scaling fix @jhkennedy 
- [x] develop percent valid scaling fix for Landsat 7 data @markf6 
- [x] provide list of all L7 granules for which the % valid needs to be fixed @jhkennedy
- [x] apply % valid fix to L7 granules @mliukis 
- [x] @chadagreene to validate

**Crop all granules**

- [x] S1 @mliukis 
- [x] S2 @mliukis 
- [x] Landsat @mliukis 
- [x] @chadagreene to validate

**Build all datacubes**

- [x] @mliukis 

**Build all composites**
- [x] Track down large v0 values that appear in mosaics
     The problem was not with re-projection but with composites code not applying threshold to X and Y components of some data variables while applying the threshold to corresponding magnitude value
- [x] @mliukis 
- [x] @chadagreene to validate

**Build all Mosaics**

- [x] @mliukis 
- [x] @chadagreene to validate

**Comment by mliukis** [comment]
v2 mosaics were generated
